spring:
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: profile-service

management:
  endpoints:
    web:
      exposure:
        include: refresh
